# Generated by Django 5.1 on 2026-07-13 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='inspections.inspectionform'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='inspectionresponse',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inspections.inspectionitem'),
        ),
        migrations.AddField(
            model_name='inspectionresponse',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inspections.inspectionreport'),
        ),
        migrations.AddIndex(
            model_name='inspectionitem',
            index=models.Index(fields=['form'], name='inspections_form_id_7758ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectionresponse',
            unique_together={('report', 'item')},
        ),
    ]
