# Generated by Django 5.1 on 2026-07-13 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('vehicles', '0002_vehicle_tank_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('target_soc', models.FloatField(default=80, help_text='Target state of charge %')),
                ('recurring_days', models.CharField(blank=True, help_text='Comma-separated day codes', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_schedules', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('energy_kwh', models.FloatField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('station_name', models.CharField(blank=True, max_length=200)),
                ('station_network', models.CharField(choices=[('chargepoint', 'ChargePoint'), ('tesla', 'Tesla Supercharger'), ('evgo', 'EVgo'), ('electrify_america', 'Electrify America'), ('other', 'Other')], default='other', max_length=30)),
                ('start_soc', models.FloatField(blank=True, help_text='Battery % at start', null=True)),
                ('end_soc', models.FloatField(blank=True, help_text='Battery % at end', null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FuelCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('provider', models.CharField(choices=[('WEX', 'WEX'), ('Comdata', 'Comdata'), ('Fleetcor', 'Fleetcor'), ('BP', 'BP'), ('other', 'Other')], default='other', max_length=20)),
                ('card_holder_name', models.CharField(blank=True, max_length=200)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_cards', to='contacts.contact')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_cards', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('e85', 'E85'), ('propane', 'Propane'), ('cng', 'CNG'), ('hydrogen', 'Hydrogen'), ('electric', 'Electric')], default='gasoline', max_length=20)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('gallons', 'Gallons'), ('liters', 'Liters')], default='gallons', max_length=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('odometer_reading', models.BigIntegerField(blank=True, null=True)),
                ('station_name', models.CharField(blank=True, max_length=200)),
                ('station_location', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='fuel-receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fuel_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fuel.fuelcard')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_transactions', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FuelFraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('wrong_fuel', 'Wrong Fuel Type'), ('double_fueling', 'Double Fueling (1hr)'), ('parked_fueling', 'Parked Vehicle Fueling'), ('excessive_qty', 'Excessive Quantity'), ('off_hours', 'Off-Hours Fueling'), ('geographic', 'Geographic Anomaly')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_alerts', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='fuel.fueltransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdlingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('fuel_burn_rate', models.FloatField(default=0.5, help_text='Gallons per hour')),
                ('fuel_price_per_gallon', models.DecimalField(decimal_places=2, default=3.5, max_digits=8)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idling_events', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['date'], name='fuel_fueltr_date_0219e8_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['fuel_type'], name='fuel_fueltr_fuel_ty_e97f97_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelfraudalert',
            index=models.Index(fields=['is_resolved'], name='fuel_fuelfr_is_reso_686c71_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelfraudalert',
            index=models.Index(fields=['severity'], name='fuel_fuelfr_severit_f8928b_idx'),
        ),
    ]
