# Generated by Django 6.0.4 on 2026-07-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcard',
            name='api_key',
            field=models.CharField(blank=True, help_text='Encrypted/stored API credential for provider sync', max_length=300),
        ),
        migrations.AddField(
            model_name='fuelcard',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelcard',
            name='provider_account_id',
            field=models.CharField(blank=True, help_text='Account ID at the card provider used for API sync', max_length=100),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='provider_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='External ID from fuel-card provider for dedup', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='fueltransaction',
            unique_together={('fuel_card', 'provider_transaction_id')},
        ),
    ]
