# Generated by Django 6.0.4 on 2026-07-19 18:40

from django.db import migrations, models


# Maps legacy FuelTransaction.fuel_type values to the unified taxonomy that
# mirrors vehicles.Vehicle.FuelType.
FUEL_TYPE_MAP = {
    'gasoline': 'Petrol',
    'diesel': 'Diesel',
    'e85': 'Ethanol (E85)',
    'propane': 'LPG',
    'cng': 'CNG',
    'hydrogen': 'Fuel Cell (Hydrogen)',
    'electric': 'Electric',
}


def normalize_fuel_types(apps, schema_editor):
    FuelTransaction = apps.get_model('fuel', 'FuelTransaction')
    for old, new in FUEL_TYPE_MAP.items():
        FuelTransaction.objects.filter(fuel_type=old).update(fuel_type=new)


def reverse_normalize(apps, schema_editor):
    FuelTransaction = apps.get_model('fuel', 'FuelTransaction')
    reverse = {v: k for k, v in FUEL_TYPE_MAP.items()}
    for new, old in reverse.items():
        FuelTransaction.objects.filter(fuel_type=new).update(fuel_type=old)


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_fuelcard_api_key_fuelcard_last_synced_at_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_fuel_types, reverse_normalize),
        migrations.AlterField(
            model_name='fueltransaction',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid (Petrol)', 'Hybrid (Petrol)'), ('Hybrid (Diesel)', 'Hybrid (Diesel)'), ('Plug-in Hybrid (Petrol)', 'Plug-in Hybrid (Petrol)'), ('Plug-in Hybrid (Diesel)', 'Plug-in Hybrid (Diesel)'), ('Mild Hybrid', 'Mild Hybrid'), ('Electric', 'Electric'), ('Fuel Cell (Hydrogen)', 'Fuel Cell (Hydrogen)'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('LNG', 'LNG'), ('Ethanol (E85)', 'Ethanol (E85)'), ('Flex Fuel', 'Flex Fuel'), ('Biodiesel', 'Biodiesel')], default='Petrol', max_length=50),
        ),
    ]
