# Generated by Django 6.0.4 on 2026-07-21 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_alter_fueltransaction_fuel_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelfraudalert',
            name='action_status',
            field=models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='fuelfraudalert',
            name='status_note',
            field=models.TextField(blank=True, help_text='Note explaining the current action status'),
        ),
        migrations.AddIndex(
            model_name='fuelfraudalert',
            index=models.Index(fields=['action_status'], name='fuel_fuelfr_action__a0cf95_idx'),
        ),
    ]
