# Generated by Django 6.0.4 on 2026-08-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0004_add_fraud_action_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('fleet', 'Fleet-wide'), ('group', 'Vehicle Group'), ('location', 'Location')], default='fleet', max_length=10)),
                ('target_ref', models.CharField(blank=True, help_text='Group/location id or name', max_length=100)),
                ('month', models.DateField(help_text='Any day in the target month; only year/month are used')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('scope', 'target_ref', 'month')},
            },
        ),
    ]
