# Generated by Django 6.0.4 on 2026-08-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0005_fuel_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelbudget',
            name='scope',
            field=models.CharField(choices=[('fleet', 'Fleet-wide'), ('vehicle_type', 'Vehicle Type'), ('location', 'Location')], default='fleet', max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelbudget',
            name='target_ref',
            field=models.CharField(blank=True, help_text='Vehicle type or location name; blank means all', max_length=100),
        ),
    ]
