# Generated by Django 5.1 on 2026-07-13 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('trigger_type', models.CharField(choices=[('time', 'Time (Months)'), ('mileage', 'Mileage'), ('engine_hours', 'Engine Hours')], default='time', max_length=20)),
                ('trigger_interval', models.IntegerField(default=6, help_text='Every X months / miles / hours')),
                ('last_triggered_value', models.BigIntegerField(default=0)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('next_due_mileage', models.BigIntegerField(blank=True, null=True)),
                ('next_due_engine_hours', models.FloatField(blank=True, null=True)),
                ('escalation_level', models.IntegerField(choices=[(0, 'None'), (1, 'Email Driver'), (2, 'SMS Manager'), (3, 'Block Dispatch')], default=0)),
                ('auto_generate_work_order', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['next_due_date', 'next_due_mileage'],
            },
        ),
    ]
