# Generated by Django 5.1 on 2026-07-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('brake_service', 'Brake Service'), ('inspection', 'Inspection'), ('repair', 'Repair'), ('preventive', 'Preventive Maintenance'), ('other', 'Other')], default='preventive', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('odometer_reading', models.BigIntegerField(blank=True, null=True)),
                ('downtime_hours', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_rating', models.FloatField(default=0, help_text='0-5')),
                ('quality_rating', models.FloatField(default=0, help_text='0-5')),
                ('turnaround_rating', models.FloatField(default=0, help_text='0-5')),
                ('overall_rating', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
