# Generated by Django 6.0.4 on 2026-08-11 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0011_vehicle_type_freeform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('part_number', models.CharField(blank=True, help_text='Manufacturer part/SKU number', max_length=100)),
                ('chemistry', models.CharField(choices=[('lead_acid', 'Lead-Acid'), ('agm', 'AGM'), ('gel', 'Gel'), ('li_ion', 'Lithium-Ion'), ('lifepo4', 'LiFePO4'), ('nicd', 'NiCd'), ('nimh', 'NiMH')], default='lead_acid', max_length=20)),
                ('voltage', models.FloatField(default=12, help_text='Nominal voltage (V)')),
                ('capacity_ah', models.FloatField(blank=True, help_text='Capacity in Amp-hours (Ah)', null=True)),
                ('cca', models.FloatField(blank=True, help_text='Cold Cranking Amps (CCA)', null=True)),
                ('rc_minutes', models.FloatField(blank=True, help_text='Reserve Capacity in minutes', null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='new', max_length=20)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('installed', 'Installed'), ('spare', 'Spare'), ('charging', 'Charging'), ('retired', 'Retired'), ('scrapped', 'Scrapped')], default='in_stock', max_length=20)),
                ('position', models.CharField(blank=True, help_text='e.g. Starter, Aux-1, House, Traction', max_length=50)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_months', models.PositiveIntegerField(blank=True, help_text='Warranty period in months', null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('install_date', models.DateField(blank=True, help_text='Date first installed in a vehicle', null=True)),
                ('last_tested', models.DateField(blank=True, help_text='Date of last load / conductance test', null=True)),
                ('expected_lifespan_months', models.PositiveIntegerField(blank=True, help_text='Expected service life in months', null=True)),
                ('group_code', models.CharField(blank=True, help_text='BCI group code, e.g. 24, 27, 31, 34, 65', max_length=30)),
                ('weight_kg', models.FloatField(blank=True, help_text='Battery weight in kilograms', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batteries', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Batteries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatteryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('install', 'Install'), ('uninstall', 'Uninstall'), ('swap', 'Swap Out'), ('charge', 'Charge'), ('retire', 'Retire')], max_length=20)),
                ('from_position', models.CharField(blank=True, max_length=50)),
                ('to_position', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='batteries.battery')),
                ('from_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battery_movements_from', to='vehicles.vehicle')),
                ('replaced_by', models.ForeignKey(blank=True, help_text='If swap, the battery that replaced this one', null=True, on_delete=django.db.models.deletion.SET_NULL, to='batteries.batterymovement')),
                ('to_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battery_movements_to', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='BatteryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateField(db_index=True)),
                ('voltage', models.FloatField(help_text='Measured voltage (V)')),
                ('specific_gravity', models.FloatField(blank=True, help_text='Electrolyte specific gravity', null=True)),
                ('internal_resistance', models.FloatField(blank=True, help_text='Internal resistance in milliohms (mΩ)', null=True)),
                ('temperature_c', models.FloatField(blank=True, help_text='Temperature at measurement (°C)', null=True)),
                ('soc_pct', models.FloatField(blank=True, help_text='State of Charge (%)', null=True)),
                ('test_result', models.CharField(choices=[('pass', 'Pass'), ('marginal', 'Marginal'), ('fail', 'Fail'), ('charge', 'Charge & Retest')], default='pass', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='batteries.battery')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battery_readings', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='BatteryReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for replacement (e.g. End of life, Failed load test, Damage)')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ordered', 'Ordered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='batteries.battery')),
                ('old_battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_records', to='batteries.battery')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battery_replacements', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargeCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('start_voltage', models.FloatField(blank=True, null=True)),
                ('end_voltage', models.FloatField(blank=True, null=True)),
                ('energy_kwh', models.FloatField(blank=True, help_text='Energy consumed during charge (kWh)', null=True)),
                ('charge_method', models.CharField(choices=[('ac', 'AC'), ('dc', 'DC'), ('regen', 'Regen'), ('alternator', 'Alternator'), ('solar', 'Solar')], default='ac', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='batteries.battery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='battery',
            index=models.Index(fields=['status'], name='batteries_b_status_9458d0_idx'),
        ),
        migrations.AddIndex(
            model_name='battery',
            index=models.Index(fields=['vehicle'], name='batteries_b_vehicle_e052dc_idx'),
        ),
        migrations.AddIndex(
            model_name='battery',
            index=models.Index(fields=['chemistry'], name='batteries_b_chemist_df4126_idx'),
        ),
        migrations.AddIndex(
            model_name='battery',
            index=models.Index(fields=['condition'], name='batteries_b_conditi_b0c6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='batterymovement',
            index=models.Index(fields=['performed_at'], name='batteries_b_perform_1a3c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='batteryreading',
            index=models.Index(fields=['measured_at'], name='batteries_b_measure_137065_idx'),
        ),
    ]
