# Generated by Django 5.1 on 2026-07-13 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('driver', 'Driver'), ('mechanic', 'Mechanic'), ('manager', 'Manager'), ('vendor', 'Vendor'), ('insurance_agent', 'Insurance Agent'), ('towing', 'Towing Company')], max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['contact_type'], name='contacts_co_contact_d678b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('license_class', models.CharField(blank=True, choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('CDL-A', 'CDL-A'), ('CDL-B', 'CDL-B'), ('M', 'Class M')], max_length=10)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('medical_card_expiry', models.DateField(blank=True, null=True)),
                ('mvr_status', models.CharField(choices=[('clean', 'Clean'), ('warning', 'Warning'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='clean', max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField(default=0, help_text='0-5 stars')),
                ('payment_terms', models.CharField(blank=True, max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to='contacts.contact')),
            ],
        ),
    ]
