# Generated by Django 6.0.4 on 2026-07-29 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('vehicles', '0011_vehicle_type_freeform'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverDrugTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('pre_employment', 'Pre-Employment'), ('random', 'Random'), ('post_accident', 'Post-Accident'), ('reasonable_suspicion', 'Reasonable Suspicion'), ('return_to_duty', 'Return to Duty'), ('follow_up', 'Follow-Up')], max_length=30)),
                ('test_date', models.DateField()),
                ('result', models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive'), ('refused', 'Refused'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('lab_name', models.CharField(blank=True, max_length=200)),
                ('chain_of_custody', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='DriverHoursOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty (Not Driving)')], max_length=20)),
                ('hours', models.FloatField(default=0, help_text='Hours in this duty status')),
                ('driving_hours', models.FloatField(default=0)),
                ('on_duty_hours', models.FloatField(default=0)),
                ('cycle_hours', models.FloatField(default=0, help_text='Cumulative cycle hours (e.g. 70/8)')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('vehicle', models.CharField(blank=True, max_length=200)),
                ('co_driver', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DriverNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General'), ('performance', 'Performance'), ('incident', 'Incident'), ('commendation', 'Commendation'), ('warning', 'Warning'), ('other', 'Other')], default='general', max_length=20)),
                ('body', models.TextField()),
                ('author', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, help_text='Percentage 0-100', null=True)),
                ('hours', models.FloatField(default=0, help_text='Training hours')),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='DriverViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('speeding', 'Speeding'), ('reckless', 'Reckless Driving'), ('dui', 'DUI / DWI'), ('following', 'Following Too Close'), ('lane', 'Improper Lane Change'), ('equipment', 'Equipment Violation'), ('accident', 'Accident'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=20)),
                ('date', models.DateField()),
                ('state', models.CharField(blank=True, max_length=10)),
                ('points', models.IntegerField(default=0, help_text='Points assigned')),
                ('description', models.TextField(blank=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/photos/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('probation', 'Probation')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='home_terminal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_endorsements',
            field=models.JSONField(blank=True, default=list, help_text='List of endorsement codes'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_state',
            field=models.CharField(blank=True, help_text='Issuing state', max_length=10),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='medical_card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='mvr_last_checked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='mvr_next_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hourly rate (0 = salary)', max_digits=10),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='pay_type',
            field=models.CharField(default='hourly', help_text='hourly, mileage, salary, percentage', max_length=20),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['employment_status'], name='contacts_dr_employm_ea9c04_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['mvr_status'], name='contacts_dr_mvr_sta_94df4e_idx'),
        ),
        migrations.AddField(
            model_name='driverassignment',
            name='driver_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='contacts.driverprofile'),
        ),
        migrations.AddField(
            model_name='driverassignment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_assignments', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='driverdrugtest',
            name='driver_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_tests', to='contacts.driverprofile'),
        ),
        migrations.AddField(
            model_name='driverhoursofservice',
            name='driver_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hos_logs', to='contacts.driverprofile'),
        ),
        migrations.AddField(
            model_name='drivernote',
            name='driver_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_log', to='contacts.driverprofile'),
        ),
        migrations.AddField(
            model_name='drivertraining',
            name='driver_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='contacts.driverprofile'),
        ),
        migrations.AddField(
            model_name='driverviolation',
            name='driver_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='contacts.driverprofile'),
        ),
        migrations.AddIndex(
            model_name='driverhoursofservice',
            index=models.Index(fields=['date'], name='contacts_dr_date_cd5d9d_idx'),
        ),
    ]
