# Generated by Django 6.0.4 on 2026-09-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_driver_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='license_class',
            field=models.CharField(blank=True, choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('AB', 'Class AB'), ('B Auto', 'Class B Auto'), ('CDL-A', 'CDL-A'), ('CDL-B', 'CDL-B'), ('M', 'Class M')], max_length=10),
        ),
    ]
