# Generated by Django 5.1 on 2026-08-12 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='priority',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['priority'], name='audit_audit_priorit_e12569_idx'),
        ),
    ]
