# Generated by Django 6.0.4 on 2026-07-31 08:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0004_alter_tenant_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_requests', models.BigIntegerField(default=0)),
                ('total_errors', models.BigIntegerField(default=0)),
                ('avg_response_ms', models.IntegerField(default=0)),
                ('top_endpoint', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EndpointUsageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-count'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('included_requests', models.BigIntegerField(default=0)),
                ('total_requests', models.BigIntegerField(default=0)),
                ('overage_requests', models.BigIntegerField(default=0)),
                ('plan_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate_per_1000', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('overage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue'), ('void', 'Void')], default='unpaid', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-billing_month'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('card', 'Card'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('wallet', 'Wallet'), ('other', 'Other')], default='card', max_length=30)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='auto_close',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='cycle_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingplan',
            name='rate_per_1000_requests',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.077'), max_digits=10),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['timestamp'], name='billing_api_timesta_472858_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['endpoint'], name='billing_api_endpoin_12a68d_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['status_code'], name='billing_api_status__d37d19_idx'),
        ),
        migrations.AddField(
            model_name='apiusagesnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='endpointusagestat',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_stats', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='billing.billingplan'),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='billing.tenantsubscription'),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_bills', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.monthlybill'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apiusagesnapshot',
            index=models.Index(fields=['date'], name='billing_api_date_60bd89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apiusagesnapshot',
            unique_together={('tenant', 'date')},
        ),
        migrations.AddIndex(
            model_name='endpointusagestat',
            index=models.Index(fields=['endpoint'], name='billing_end_endpoin_eb419e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='endpointusagestat',
            unique_together={('tenant', 'date', 'endpoint', 'method')},
        ),
        migrations.AddIndex(
            model_name='monthlybill',
            index=models.Index(fields=['status'], name='billing_mon_status_03384d_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlybill',
            index=models.Index(fields=['billing_month'], name='billing_mon_billing_dbfc1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybill',
            unique_together={('tenant', 'billing_month')},
        ),
    ]
