# Generated by Django 6.0.4 on 2026-07-31 09:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billing_expanded'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, unique=True)),
                ('rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['currency'],
            },
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='billing_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='grand_total_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='grand_total_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='rate_per_1000_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.077'), max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='tax_amount_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='tax_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='usage_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='usage_cost_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='billing_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='rate_per_1000_requests',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.077'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.billingplan'),
        ),
    ]
