# Generated by Django 6.0.4 on 2026-07-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverQualificationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending Review'), ('complete', 'Complete'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='incomplete', max_length=20)),
                ('application_date', models.DateField(blank=True, help_text='Date driver applied / was hired', null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, help_text='Annual DQF review date', null=True)),
                ('next_review_due', models.DateField(blank=True, null=True)),
                ('road_test_passed', models.BooleanField(default=False)),
                ('road_test_date', models.DateField(blank=True, null=True)),
                ('road_test_examiner', models.CharField(blank=True, max_length=200)),
                ('background_check_passed', models.BooleanField(default=False)),
                ('background_check_date', models.DateField(blank=True, null=True)),
                ('drug_test_passed', models.BooleanField(default=False)),
                ('drug_test_date', models.DateField(blank=True, null=True)),
                ('medical_examiner', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(limit_choices_to={'contact_type': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='dqf', to='contacts.contact')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DqfCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('application', 'Employment Application'), ('road_test', 'Road Test'), ('background_check', 'Background Check'), ('drug_test', 'Pre-employment Drug Test'), ('mvr_check', 'Motor Vehicle Record (MVR)'), ('medical_card', 'Medical Examiner Certificate'), ('license_check', 'Commercial License Verification'), ('psp', 'Pre-employment Screening Program (PSP)'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('flagged', 'Flagged'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('result_notes', models.TextField(blank=True)),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dqf_checks', to='documents.document')),
                ('dqf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='dqf.driverqualificationfile')),
            ],
            options={
                'ordering': ['check_type'],
                'unique_together': {('dqf', 'check_type')},
            },
        ),
    ]
