# Generated by Django 6.0.4 on 2026-09-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('issues', '0003_issuephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='contacts.contact'),
        ),
    ]
