# Generated by Django 5.1 on 2026-07-13 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('vehicles', '0002_vehicle_tank_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious'), ('fatal', 'Fatal')], default='minor', max_length=10)),
                ('weather', models.CharField(choices=[('clear', 'Clear'), ('rain', 'Rain'), ('snow', 'Snow'), ('fog', 'Fog'), ('storm', 'Storm')], default='clear', max_length=10)),
                ('road_condition', models.CharField(choices=[('dry', 'Dry'), ('wet', 'Wet'), ('icy', 'Icy'), ('snow_covered', 'Snow Covered'), ('construction', 'Under Construction')], default='dry', max_length=20)),
                ('description', models.TextField()),
                ('fault_tree_analysis', models.TextField(blank=True, help_text='Root cause analysis of the accident')),
                ('police_report_number', models.CharField(blank=True, max_length=100)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='accident-photos/')),
                ('estimated_damage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_accidents', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents', to='contacts.contact')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AccidentWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_info', models.CharField(blank=True, max_length=200)),
                ('statement', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='accidents.accidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(blank=True, max_length=100)),
                ('insurance_company', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('denied', 'Denied'), ('settled', 'Settled'), ('litigation', 'In Litigation')], default='filed', max_length=20)),
                ('claim_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('settled_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claim', to='accidents.accidentreport')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims', to='contacts.contact')),
            ],
        ),
    ]
