# Generated by Django 6.0.4 on 2026-07-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=25),
        ),
    ]
