# Generated by Django 6.0.4 on 2026-07-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0002_accidentreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accident-photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accident_photos', to='accidents.accidentreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
