# Generated by Django 6.0.4 on 2026-08-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0003_accident_photos'),
        ('rentals', '0015_driver_hire_effective_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents', to='rentals.customer'),
        ),
    ]
