# Generated by Django 6.0.4 on 2026-09-05 20:03

from django.db import migrations


def seed_rbac(apps, schema_editor):
    """Seed RBAC permissions and system roles for the current schema.

    This runs once per tenant schema (django-tenants runs migrations
    schema-by-schema). It delegates to the same logic used by the
    ``sync_permissions`` management command so the registry is always
    the single source of truth.
    """
    from apps.rbac.models import Permission, Role
    from apps.rbac.permissions_registry import PERMISSIONS_REGISTRY, SYSTEM_ROLES

    # 1. Sync permissions from registry
    perm_map = {}
    for module, label, icon, actions in PERMISSIONS_REGISTRY:
        for action, action_label, desc in actions:
            perm, _ = Permission.objects.update_or_create(
                module=module,
                action=action,
                defaults={'label': action_label, 'description': desc},
            )
            perm_map[(module, action)] = perm

    # 2. Sync system roles (create if missing, reconcile permissions)
    for role_data in SYSTEM_ROLES:
        role, created = Role.objects.get_or_create(
            key=role_data['key'],
            defaults={
                'name': role_data['name'],
                'description': role_data['description'],
                'color': role_data['color'],
                'icon': role_data['icon'],
                'is_system': role_data['is_system'],
                'is_default': role_data['is_default'],
            },
        )
        if created:
            perm_objs = [
                perm_map[(m, a)] for m, a in role_data['permissions']
                if (m, a) in perm_map
            ]
            role.permissions.set(perm_objs)


def reverse_seed(apps, schema_editor):
    """No-op reverse: we don't want to delete data on rollback."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_rbac, reverse_seed),
    ]
