# Generated by Django 6.0.4 on 2026-09-05 20:27

from django.db import migrations


def sync_rbac(apps, schema_editor):
    """Sync the new ``transfers`` permissions and reconcile system roles.

    Reuses the same logic as the ``sync_permissions`` management command:
    create any new Permission rows, ensure system roles exist, and add
    new permissions to existing system roles (without removing customizations).
    """
    from apps.rbac.models import Permission, Role
    from apps.rbac.permissions_registry import PERMISSIONS_REGISTRY, SYSTEM_ROLES

    # 1. Sync permissions from registry
    perm_map = {}
    for module, label, icon, actions in PERMISSIONS_REGISTRY:
        for action, action_label, desc in actions:
            perm, _ = Permission.objects.update_or_create(
                module=module,
                action=action,
                defaults={'label': action_label, 'description': desc},
            )
            perm_map[(module, action)] = perm

    # 2. Reconcile system roles: create missing, add missing permissions
    for role_data in SYSTEM_ROLES:
        role, created = Role.objects.get_or_create(
            key=role_data['key'],
            defaults={
                'name': role_data['name'],
                'description': role_data['description'],
                'color': role_data['color'],
                'icon': role_data['icon'],
                'is_system': role_data['is_system'],
                'is_default': role_data['is_default'],
            },
        )
        if created:
            perm_objs = [
                perm_map[(m, a)] for m, a in role_data['permissions']
                if (m, a) in perm_map
            ]
            role.permissions.set(perm_objs)
        else:
            # Ensure any NEW permissions from the registry are added
            # (don't remove existing ones — admin may have customized)
            existing_perm_ids = set(role.permissions.values_list('id', flat=True))
            for module, action in role_data['permissions']:
                perm = perm_map.get((module, action))
                if perm and perm.id not in existing_perm_ids:
                    role.permissions.add(perm)


def reverse_sync(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_seed_rbac_permissions_roles'),
    ]

    operations = [
        migrations.RunPython(sync_rbac, reverse_sync),
    ]
