# Generated by Django 6.0.4 on 2026-07-26 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0009_vehicle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('local', 'Local'), ('foreigner', 'Foreigner')], default='local', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, help_text='Country of residence', max_length=80)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('driver_license', "Driver's License"), ('alien_card', 'Alien Card')], default='national_id', max_length=20)),
                ('id_number', models.CharField(max_length=80)),
                ('driving_license_no', models.CharField(blank=True, max_length=80)),
                ('license_issued_country', models.CharField(blank=True, max_length=80)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_no', models.CharField(editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='draft', max_length=20)),
                ('rate_period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('weekend', 'Weekend')], default='daily', max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weekly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weekend_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pickup_location', models.CharField(blank=True, max_length=200)),
                ('dropoff_location', models.CharField(blank=True, max_length=200)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('actual_return_datetime', models.DateTimeField(blank=True, null=True)),
                ('insurance_type', models.CharField(blank=True, help_text='CDW, Third-Party, Comprehensive, etc.', max_length=40)),
                ('insurance_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gps_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('child_seat_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('additional_driver_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentage 0–100', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('damage_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_mileage', models.PositiveIntegerField(default=0, help_text='Free km allowed')),
                ('excess_mileage_rate', models.DecimalField(decimal_places=2, default=0, help_text='Per extra km', max_digits=12)),
                ('start_mileage', models.FloatField(blank=True, null=True)),
                ('end_mileage', models.FloatField(blank=True, null=True)),
                ('fuel_policy', models.CharField(choices=[('full_full', 'Full to Full'), ('prepaid', 'Prepaid'), ('half_tank', 'Half Tank')], default='full_full', max_length=20)),
                ('start_fuel_level', models.CharField(blank=True, default='full', max_length=20)),
                ('end_fuel_level', models.CharField(blank=True, max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='rental-agreements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='rentals.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_agreements', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Rental Agreement',
                'verbose_name_plural': 'Rental Agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('customer', 'Customer'), ('company_rep', 'Company Representative')], default='customer', max_length=20)),
                ('signatory_name', models.CharField(blank=True, max_length=200)),
                ('signature_data', models.TextField(help_text='SVG path string or data URL of drawn signature')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='rentals.rentalagreement')),
            ],
            options={
                'verbose_name': 'Digital Signature',
                'verbose_name_plural': 'Digital Signatures',
                'ordering': ['signed_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('base_rental', 'Base Rental'), ('insurance', 'Insurance'), ('gps', 'GPS'), ('child_seat', 'Child Seat'), ('additional_driver', 'Additional Driver'), ('delivery', 'Delivery'), ('late_return', 'Late Return'), ('excess_mileage', 'Excess Mileage'), ('fuel_refill', 'Fuel Refill'), ('cleaning', 'Cleaning'), ('damage', 'Damage'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='rentals.rentalagreement')),
            ],
            options={
                'verbose_name': 'Rental Charge',
                'verbose_name_plural': 'Rental Charges',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='e.g. Front bumper, Driver door', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('none', 'None'), ('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=20)),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='rental-damages/')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='rentals.rentalagreement')),
            ],
            options={
                'verbose_name': 'Vehicle Damage',
                'verbose_name_plural': 'Vehicle Damages',
                'ordering': ['recorded_at'],
            },
        ),
    ]
