# Generated by Django 6.0.4 on 2026-07-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(help_text='Key from EXTRAS_CATALOG or custom', max_length=40)),
                ('item_name', models.CharField(help_text='Display name', max_length=120)),
                ('status', models.CharField(choices=[('present', 'Present'), ('missing', 'Missing'), ('damaged', 'Damaged'), ('n_a', 'N/A')], default='present', max_length=20)),
                ('stage', models.CharField(choices=[('pickup', 'Pickup'), ('return', 'Return')], default='pickup', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_checks', to='rentals.rentalagreement')),
            ],
            options={
                'verbose_name': 'Vehicle Check',
                'verbose_name_plural': 'Vehicle Checks',
                'ordering': ['item_key', 'stage'],
                'unique_together': {('agreement', 'item_key', 'stage')},
            },
        ),
    ]
