# Generated by Django 6.0.4 on 2026-07-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_customer_latitude_customer_longitude_and_more'),
        ('vehicles', '0009_vehicle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('apply_to', models.CharField(choices=[('group', 'Group'), ('individual', 'Individual')], default='group', max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weekly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weekend_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custom_rate_label', models.CharField(blank=True, help_text='Label for the custom rate, e.g. "3-Day Package"', max_length=80)),
                ('custom_rate_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custom_rate_days', models.PositiveIntegerField(default=0, help_text='Number of days the custom rate covers')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('damage_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_mileage', models.PositiveIntegerField(default=0, help_text='Free miles/km per day (0 = unlimited)')),
                ('excess_mileage_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('insurance_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gps_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('child_seat_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('additional_driver_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('driver_fee', models.DecimalField(decimal_places=2, default=0, help_text='Per-driver fee', max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prep_fee', models.DecimalField(decimal_places=2, default=0, help_text='Vehicle preparation / cleaning fee', max_digits=12)),
                ('after_hours_fee', models.DecimalField(decimal_places=2, default=0, help_text='After-hours pickup/drop-off fee', max_digits=12)),
                ('underage_fee', models.DecimalField(decimal_places=2, default=0, help_text='Young driver surcharge', max_digits=12)),
                ('one_way_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_plans', to='vehicles.vehicle')),
                ('vehicle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_plans', to='vehicles.fleetgroup')),
            ],
            options={
                'verbose_name': 'Vehicle Pricing Plan',
                'verbose_name_plural': 'Vehicle Pricing Plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
