# Generated by Django 6.0.4 on 2026-07-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_vehiclepricing'),
        ('vehicles', '0009_vehicle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclepricing',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='vehiclepricing',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='daily_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='monthly_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='pricing_plans', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='weekend_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='weekly_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vehiclepricing',
            name='apply_to',
            field=models.CharField(choices=[('group', 'Group'), ('vehicles', 'Specific Vehicles')], default='group', max_length=20),
        ),
    ]
