# Generated by Django 6.0.4 on 2026-07-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_vehiclepricing_discount_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclepricing',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='General deposit amount', max_digits=12),
        ),
    ]
