# Generated by Django 6.0.4 on 2026-07-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_rename_discount_amount_to_deposit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclepricing',
            name='weekend_discount_percent',
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='weekend_markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage increase applied to the base weekend rate', max_digits=5),
        ),
    ]
