# Generated by Django 6.0.4 on 2026-07-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_rename_weekend_discount_to_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepricing',
            name='daily_markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage increase applied to the base daily rate', max_digits=5),
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='monthly_markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage increase applied to the base monthly rate', max_digits=5),
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='weekend_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='weekly_markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage increase applied to the base weekly rate', max_digits=5),
        ),
    ]
