# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_add_markup_percent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='driving_license_image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
    ]
