# Generated by Django 6.0.4 on 2026-07-28 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_customer_document_images'),
        ('vehicles', '0011_vehicle_type_freeform'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepricing',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_plans', to='vehicles.vehicletype'),
        ),
    ]
