# Generated by Django 6.0.4 on 2026-07-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('rentals', '0010_pricing_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Assigned driver (optional, from contacts with type "Driver")', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_agreements_as_driver', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='driver_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daily rate paid to the assigned driver', max_digits=12),
        ),
    ]
