# Generated by Django 6.0.4 on 2026-07-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_driver_management'),
        ('rentals', '0012_rentalpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverHireRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Plan label, e.g. "Corporate Weekend plan"', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('default_rate_period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('weekend', 'Weekend')], default='daily', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weekly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weekend_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hourly_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('daily_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weekly_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monthly_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weekend_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hourly_markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('daily_markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weekly_markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monthly_markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weekend_markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('markup_flat_amount', models.DecimalField(decimal_places=2, default=0, help_text='Flat markup amount added on top of the computed rate (per billing period)', max_digits=12)),
                ('discount_flat_amount', models.DecimalField(decimal_places=2, default=0, help_text='Flat discount amount subtracted after the percentage discount', max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Use as the default plan when creating a new hire for this customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer who hires drivers under this rate plan', on_delete=django.db.models.deletion.CASCADE, related_name='driver_hire_rates', to='rentals.customer')),
                ('driver', models.ForeignKey(blank=True, help_text='Optional: rate applies to a specific driver (null = default rate for the customer)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_hire_rates', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Driver Hire Rate',
                'verbose_name_plural': 'Driver Hire Rates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='rentals_dri_custome_e87adb_idx')],
            },
        ),
    ]
