# Generated by Django 6.0.4 on 2026-07-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_driver_management'),
        ('rentals', '0013_driver_hire_rates'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='driverhirerate',
            name='rentals_dri_custome_e87adb_idx',
        ),
        migrations.AddIndex(
            model_name='driverhirerate',
            index=models.Index(fields=['status'], name='rentals_dri_status_6ccaff_idx'),
        ),
        migrations.RemoveField(
            model_name='driverhirerate',
            name='customer',
        ),
    ]
