# Generated by Django 6.0.4 on 2026-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0014_driver_hire_rate_remove_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverhirerate',
            name='daily_effective_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-computed: base × (1 − disc%) × (1 + markup%)', max_digits=12),
        ),
        migrations.AddField(
            model_name='driverhirerate',
            name='hourly_effective_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-computed: base × (1 − disc%) × (1 + markup%)', max_digits=12),
        ),
        migrations.AddField(
            model_name='driverhirerate',
            name='monthly_effective_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-computed: base × (1 − disc%) × (1 + markup%)', max_digits=12),
        ),
        migrations.AddField(
            model_name='driverhirerate',
            name='weekend_effective_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-computed: base × (1 − disc%) × (1 + markup%)', max_digits=12),
        ),
        migrations.AddField(
            model_name='driverhirerate',
            name='weekly_effective_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-computed: base × (1 − disc%) × (1 + markup%)', max_digits=12),
        ),
    ]
