# Generated by Django 5.1 on 2026-08-12 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_driver_hire_effective_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='inspection_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='InspectionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(help_text='Key from INSPECTION_CATALOG or custom', max_length=40)),
                ('item_name', models.CharField(help_text='Display name', max_length=120)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warning', 'Warning'), ('n_a', 'N/A')], default='pass', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_checks', to='rentals.rentalagreement')),
            ],
            options={
                'verbose_name': 'Inspection Check',
                'verbose_name_plural': 'Inspection Checks',
                'ordering': ['item_key'],
                'unique_together': {('agreement', 'item_key')},
            },
        ),
    ]
