# Generated by Django 5.1 on 2026-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0016_inspection_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectioncheck',
            name='failed_parts',
            field=models.JSONField(blank=True, default=list, help_text='List of specific sub-items that failed (e.g. left headlight)'),
        ),
    ]
