# Generated by Django 6.0.4 on 2026-08-31 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0018_invoice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='agreements',
            field=models.JSONField(blank=True, default=list, help_text='List of {id, agreement_no} for multi-agreement consolidated invoices.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='agreement',
            field=models.ForeignKey(blank=True, help_text='Primary agreement for single-agreement invoices; null for multi-agreement consolidated invoices.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='rentals.rentalagreement'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
