# Generated by Django 6.0.4 on 2026-08-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0020_invoice_multi_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_to',
            field=models.JSONField(blank=True, default=dict, help_text='Billing recipient details {name, company, address, email, phone} for customized invoices.'),
        ),
    ]
