# Generated by Django 6.0.4 on 2026-08-31 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0021_invoice_to_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Linked customer for agreement-based invoices; null for standalone custom invoices.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='rentals.customer'),
        ),
    ]
