# Generated by Django 6.0.4 on 2026-08-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0022_invoice_customer_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='branding_color',
            field=models.CharField(blank=True, default='#0d9488', help_text='Hex color used to brand the invoice (header, totals, accents).', max_length=7),
        ),
    ]
