# Generated by Django 6.0.4 on 2026-09-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0023_invoice_branding_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='terms_and_conditions',
            field=models.JSONField(blank=True, default=list, help_text='Editable list of {id, title, text} clauses for this agreement'),
        ),
    ]
