# Generated by Django 6.0.4 on 2026-09-06 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0024_terms_and_conditions_field'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transfer',
            field=models.ForeignKey(blank=True, help_text='Linked transfer booking for transfer-generated invoices.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='transfers.transfer'),
        ),
    ]
