# Generated by Django 5.1 on 2026-07-13 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0002_initial'),
        ('vehicles', '0002_vehicle_tank_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bay_type', models.CharField(choices=[('lift', 'Lift Bay'), ('flat', 'Flat Bay'), ('paint', 'Paint Bay'), ('wash', 'Wash Bay'), ('inspection', 'Inspection Bay'), ('general', 'General Bay')], default='general', max_length=20)),
                ('capacity', models.IntegerField(default=1, help_text='Number of vehicles per bay')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BayReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bay_reservations', to='vehicles.vehicle')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bay_reservations', to='issues.workorder')),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='garage.garagebay')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
