# Generated by Django 6.0.4 on 2026-07-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessor_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('national_id', models.CharField(blank=True, help_text='National identity / ID number', max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('representative_name', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, help_text='Company registration / tax ID', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company_name', 'first_name', 'last_name'],
                'indexes': [models.Index(fields=['lessor_type'], name='lessors_les_lessor__4a844d_idx')],
            },
        ),
    ]
