# Generated by Django 6.0.4 on 2026-07-31 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessor',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Bank account for payments', max_length=100),
        ),
        migrations.AddField(
            model_name='lessor',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='Master contract end', null=True),
        ),
        migrations.AddField(
            model_name='lessor',
            name='contract_start_date',
            field=models.DateField(blank=True, help_text='Master contract start', null=True),
        ),
        migrations.AddField(
            model_name='lessor',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='e.g. Net 30, Monthly in advance', max_length=200),
        ),
        migrations.AddField(
            model_name='lessor',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax identification number', max_length=50),
        ),
        migrations.CreateModel(
            name='LessorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, help_text='Unique contract reference', max_length=100)),
                ('title', models.CharField(default='Lease Agreement', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('pending', 'Pending Signature')], default='draft', max_length=20)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Monthly lease rate in USD', max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('terms', models.TextField(blank=True, help_text='Lease terms and conditions')),
                ('mileage_limit', models.IntegerField(blank=True, help_text='Monthly mileage limit', null=True)),
                ('excess_mileage_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per unit over mileage limit', max_digits=10, null=True)),
                ('insurance_required', models.BooleanField(default=True)),
                ('maintenance_responsibility', models.CharField(blank=True, help_text='Who handles maintenance: lessor, lessee, or shared', max_length=50)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='lessors.lessor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('insurance', 'Insurance'), ('registration', 'Registration'), ('license', 'License'), ('tax', 'Tax Document'), ('bank', 'Bank Document'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='lessor-documents/')),
                ('file_url', models.URLField(blank=True, help_text='External URL if not uploading a file')),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lessors.lessor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('wire', 'Wire'), ('card', 'Card'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Payment reference / transaction ID', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='lessors.lessorcontract')),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lessors.lessor')),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lessorcontract',
            index=models.Index(fields=['lessor', 'status'], name='lessors_les_lessor__e5aaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='lessorpayment',
            index=models.Index(fields=['lessor', 'status'], name='lessors_les_lessor__d52d53_idx'),
        ),
    ]
