# Generated by Django 5.1 on 2026-07-13 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('trailer', 'Trailer'), ('equipment', 'Equipment'), ('non_powered', 'Non-powered Asset')], default='vehicle', max_length=20)),
                ('fuel_type', models.CharField(choices=[('ICE', 'ICE'), ('EV', 'EV'), ('Hybrid', 'Hybrid')], default='ICE', max_length=10)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('current_mileage', models.BigIntegerField(default=0)),
                ('engine_hours', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('out_of_service', 'Out of Service'), ('in_maintenance', 'In Maintenance'), ('retired', 'Retired')], default='active', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('battery_capacity_kwh', models.FloatField(blank=True, null=True)),
                ('state_of_charge', models.FloatField(blank=True, help_text='Percentage 0-100', null=True)),
                ('state_of_health', models.FloatField(blank=True, help_text='Percentage 0-100', null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('useful_life_years', models.IntegerField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, max_length=100)),
                ('transmission', models.CharField(blank=True, max_length=100)),
                ('weight_rating', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, limit_choices_to={'contact_type': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='contacts.contact')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.fleetgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(choices=[('mileage', 'Mileage'), ('engine_hours', 'Engine Hours')], default='mileage', max_length=20)),
                ('value', models.BigIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_entries', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='vehicles_ve_status_f71f77_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['group'], name='vehicles_ve_group_i_3b02b8_idx'),
        ),
    ]
