# Generated by Django 5.1 on 2026-07-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tank_capacity',
            field=models.FloatField(blank=True, help_text='Fuel tank capacity in gallons', null=True),
        ),
    ]
