# Generated by Django 6.0.4 on 2026-07-17 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessors', '0001_initial'),
        ('vehicles', '0002_vehicle_tank_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='lease_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lease_monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lease_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='lessors.lessor'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage_unit',
            field=models.CharField(choices=[('miles', 'Miles'), ('km', 'Kilometers')], default='km', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ownership',
            field=models.CharField(choices=[('self', 'Owned (Self)'), ('lease', 'Leased')], default='self', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_mileage',
            field=models.BigIntegerField(default=0, help_text='Odometer reading in the selected mileage unit'),
        ),
    ]
