# Generated by Django 6.0.4 on 2026-07-17 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_lease_end_date_vehicle_lease_monthly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, help_text='Display label (defaults to name)', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes/No'), ('select', 'Dropdown')], default='text', max_length=20)),
                ('choices', models.JSONField(blank=True, default=list, help_text='Allowed values for select fields')),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='depreciation_method',
            field=models.CharField(choices=[('straight_line', 'Straight-Line'), ('declining_balance', 'Declining Balance'), ('none', 'None')], default='straight_line', max_length=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gross_vehicle_weight',
            field=models.FloatField(blank=True, help_text='GVWR in lbs', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='in_service_date',
            field=models.DateField(blank=True, help_text='Date the vehicle entered service', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_premium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual insurance premium', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Financing monthly payment', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='out_of_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='residual_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Residual / salvage value', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='retired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='trim',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='vehicles.customfield')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['field__name'],
                'unique_together': {('vehicle', 'field')},
            },
        ),
    ]
