# Generated by Django 5.1 on 2026-07-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_lifecycle_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lease security deposit', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_type',
            field=models.CharField(blank=True, default='', help_text='Insurance coverage type', max_length=50),
        ),
    ]
