# Generated by Django 6.0.4 on 2026-07-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehiclebodytype_vehiclemake_vehiclemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='comfort_convenience',
            field=models.JSONField(blank=True, default=list, help_text='Comfort & Convenience options'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='dress_up',
            field=models.JSONField(blank=True, default=list, help_text='Dress-up / styling options'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drivetrain',
            field=models.CharField(blank=True, choices=[('2WD', '2WD'), ('4WD', '4WD'), ('4-2', '4x2'), ('4-4', '4x4'), ('6-2', '6x2'), ('6-4', '6x4'), ('8-4', '8x4')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='exterior_color_custom',
            field=models.CharField(blank=True, default='', help_text='Custom hex color when exterior color is "other"', max_length=7),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='exterior_features',
            field=models.JSONField(blank=True, default=list, help_text='Exterior feature options'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='safety_features',
            field=models.JSONField(blank=True, default=list, help_text='Safety & assistance options'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='steering',
            field=models.CharField(blank=True, choices=[('left', 'Left Hand'), ('right', 'Right Hand')], default='', max_length=10),
        ),
    ]
