# Generated by Django 6.0.4 on 2026-07-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_comfort_convenience_vehicle_dress_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='engine_size',
            field=models.CharField(blank=True, default='', help_text='Engine displacement in cc, e.g. 2000cc', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='motors',
            field=models.CharField(blank=True, default='', help_text='Electric motor configuration, e.g. Dual Motor', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=50),
        ),
    ]
