# Generated by Django 5.1 on 2026-07-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehicle_engine_size_vehicle_motors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, help_text='Vehicle photo', null=True, upload_to='vehicles/'),
        ),
    ]
