# Generated by Django 6.0.4 on 2026-07-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_vehicle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='mdi-car', help_text='Material Design Icon name', max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Hex colour for chips / badges', max_length=7)),
                ('passenger_capacity', models.PositiveIntegerField(default=0, help_text='Max passengers (0 = not specified)')),
                ('cargo_capacity_kg', models.FloatField(default=0, help_text='Cargo capacity in kg (0 = not specified)')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower values appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
