# Generated by Django 6.0.4 on 2026-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, default='', help_text='Fleet vehicle category (e.g. SUV, Mini-van, Truck) — managed in the Vehicle Types tab', max_length=100),
        ),
    ]
