# Generated by Django 6.0.4 on 2026-07-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('insurance', 'Insurance'), ('registration', 'Registration'), ('title', 'Title'), ('inspection', 'Inspection'), ('license', 'License'), ('medical_card', 'Medical Card'), ('warranty', 'Warranty'), ('contract', 'Contract'), ('permit', 'Permit'), ('maintenance', 'Maintenance Record'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
