# Generated by Django 6.0.4 on 2026-07-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0004_vehicle_lifecycle_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, help_text='e.g. 11R22.5', max_length=50)),
                ('type', models.CharField(blank=True, help_text='e.g. Steer, Drive, Trailer', max_length=50)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('mounted', 'Mounted'), ('spare', 'Spare'), ('retired', 'Retired'), ('scrapped', 'Scrapped')], default='in_stock', max_length=20)),
                ('position', models.CharField(blank=True, help_text='e.g. FL_Outer, RR_Inner', max_length=20)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_miles', models.FloatField(blank=True, null=True)),
                ('min_tread_depth', models.FloatField(default=4, help_text='Retread/replace threshold in 32nds of an inch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tires', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TireInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tread_depth', models.FloatField(help_text='Tread depth in 32nds of an inch')),
                ('pressure_psi', models.FloatField(blank=True, null=True)),
                ('odometer', models.FloatField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('worn', 'Worn'), ('damaged', 'Damaged'), ('ok', 'OK')], default='ok', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('measured_at', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='tires.tire')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_inspections', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='TireMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('mount', 'Mount'), ('unmount', 'Unmount'), ('transfer', 'Transfer'), ('retread', 'Retread')], max_length=20)),
                ('from_position', models.CharField(blank=True, max_length=20)),
                ('to_position', models.CharField(blank=True, max_length=20)),
                ('odometer', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_movements_from', to='vehicles.vehicle')),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='tires.tire')),
                ('to_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_movements_to', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='TireRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateField(db_index=True)),
                ('rotation_pattern', models.CharField(blank=True, help_text='e.g. Front-to-rear, X-pattern', max_length=50)),
                ('odometer', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_rotations', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tire',
            index=models.Index(fields=['status'], name='tires_tire_status_c533b4_idx'),
        ),
        migrations.AddIndex(
            model_name='tire',
            index=models.Index(fields=['vehicle'], name='tires_tire_vehicle_5bdfaf_idx'),
        ),
    ]
