# Generated by Django 6.0.4 on 2026-07-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of identical tires in stock for this line item'),
        ),
    ]
