# Generated by Django 6.0.4 on 2026-07-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0002_tire_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('second_hand', 'Second Hand'), ('retreaded', 'Retreaded'), ('reclaimed', 'Reclaimed'), ('used', 'Used')], default='new', max_length=20),
        ),
    ]
