# Generated by Django 6.0.4 on 2026-07-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0003_tire_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirerotation',
            name='swaps',
            field=models.JSONField(blank=True, help_text='Array of swap objects: {tire, from_position, to_position}', null=True),
        ),
    ]
