# Generated by Django 6.0.4 on 2026-07-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_name_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
