# Generated by Django 5.1 on 2026-08-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
