# Generated by Django 6.0.4 on 2026-07-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('fuel', '0002_fuelcard_api_key_fuelcard_last_synced_at_and_more'),
        ('vehicles', '0004_vehicle_lifecycle_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='IFTA jurisdiction code, e.g. CA, TX, ON', max_length=4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('fuel_tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='Tax rate per gallon', max_digits=8)),
                ('is_ifta', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IftaQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 (Jan–Mar)'), ('Q2', 'Q2 (Apr–Jun)'), ('Q3', 'Q3 (Jul–Sep)'), ('Q4', 'Q4 (Oct–Dec)')], max_length=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('filed', 'Filed')], default='draft', max_length=20)),
                ('total_miles', models.FloatField(default=0)),
                ('total_gallons', models.FloatField(default=0)),
                ('total_tax_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifta_quarters', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-year', '-quarter'],
                'unique_together': {('vehicle', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='FuelPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('gallons', models.FloatField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_paid', models.DecimalField(decimal_places=2, default=0, help_text='Fuel tax already paid at the pump', max_digits=12)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('fuel_card', 'Fuel Card')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fuel_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ifta_purchases', to='fuel.fueltransaction')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifta_fuel_purchases', to='vehicles.vehicle')),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_purchases', to='ifta.jurisdiction')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['vehicle', 'date'], name='ifta_fuelpu_vehicle_a4d3e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_odometer', models.FloatField(blank=True, null=True)),
                ('end_odometer', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(default=0, help_text='Distance traveled in this jurisdiction')),
                ('distance_unit', models.CharField(choices=[('miles', 'Miles'), ('km', 'Kilometers')], default='miles', max_length=10)),
                ('trip_type', models.CharField(choices=[('loaded', 'Loaded'), ('empty', 'Empty'), ('bobtail', 'Bobtail')], default='loaded', max_length=20)),
                ('route', models.CharField(blank=True, help_text='From / To description', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('telematics', 'Telematics')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ifta_trip_logs', to='contacts.contact')),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_logs', to='ifta.jurisdiction')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifta_trip_logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['vehicle', 'date'], name='ifta_triplo_vehicle_d10477_idx')],
            },
        ),
    ]
