# Generated by Django 6.0.4 on 2026-07-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0002_initial'),
        ('vehicles', '0004_vehicle_lifecycle_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('recall_type', models.CharField(choices=[('safety_recall', 'Safety Recall'), ('campaign', 'Service Campaign'), ('field_notice', 'Field Notice'), ('emission', 'Emission Recall')], default='safety_recall', max_length=20)),
                ('nhtsa_campaign_number', models.CharField(blank=True, help_text='NHTSA recall campaign number', max_length=50)),
                ('manufacturer_campaign_number', models.CharField(blank=True, max_length=50)),
                ('oem', models.CharField(blank=True, help_text='Manufacturer / OEM issuing the recall', max_length=100)),
                ('component', models.CharField(blank=True, help_text='Affected component, e.g. Brakes, Fuel System', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('remedy', models.TextField(blank=True)),
                ('risk', models.TextField(blank=True, help_text='Safety risk if not addressed')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('is_critical', models.BooleanField(default=False)),
                ('affected_make', models.CharField(blank=True, help_text='Applies to vehicles of this make', max_length=100)),
                ('affected_models', models.TextField(blank=True, help_text='Comma-separated models')),
                ('affected_year_from', models.IntegerField(blank=True, null=True)),
                ('affected_year_to', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='recalls_rec_status_f4e0d2_idx'), models.Index(fields=['recall_type'], name='recalls_rec_recall__d161e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecallVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('affected', 'Affected'), ('scheduled', 'Repair Scheduled'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('not_affected', 'Not Affected')], default='affected', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='recalls.recall')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='vehicles.vehicle')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_vehicles', to='issues.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('recall', 'vehicle')},
            },
        ),
    ]
