# Generated by Django 6.0.4 on 2026-07-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('depot', 'Depot / Yard'), ('fuel_station', 'Fuel Station'), ('charging_station', 'Charging Station'), ('warehouse', 'Warehouse'), ('customer_site', 'Customer Site'), ('geopoint', 'Geofence Point'), ('other', 'Other')], default='other', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_geofence', models.BooleanField(default=False)),
                ('shape', models.CharField(choices=[('circle', 'Circle'), ('polygon', 'Polygon')], default='circle', max_length=20)),
                ('radius_meters', models.FloatField(blank=True, help_text='Radius for circle geofences', null=True)),
                ('polygon', models.JSONField(blank=True, default=list, help_text='List of [lat, lng] coordinates for polygon geofences')),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
