# Generated by Django 6.0.4 on 2026-07-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
