# Generated by Django 6.0.4 on 2026-08-31 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0011_vehicle_type_freeform'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(editable=False, max_length=40, unique=True)),
                ('bank_name', models.CharField(help_text='Financial institution / bank name', max_length=200)),
                ('branch', models.CharField(blank=True, default='', max_length=200)),
                ('account_no', models.CharField(blank=True, default='', help_text='Bank account/loan account number', max_length=100)),
                ('disbursement_date', models.DateField(blank=True, help_text='Date funds were disbursed', null=True)),
                ('first_payment_date', models.DateField(blank=True, help_text='First instalment due date', null=True)),
                ('maturity_date', models.DateField(blank=True, help_text='Expected loan completion date', null=True)),
                ('closed_date', models.DateField(blank=True, help_text='Date loan was fully settled', null=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total loan principal', max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=0, help_text='Annual interest rate (%)', max_digits=8)),
                ('interest_type', models.CharField(choices=[('fixed', 'Fixed'), ('floating', 'Floating'), ('reducing', 'Reducing Balance')], default='fixed', max_length=20)),
                ('tenor_months', models.IntegerField(default=0, help_text='Loan tenor in months')),
                ('monthly_instalment', models.DecimalField(decimal_places=2, default=0, help_text='EMI amount', max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_premium', models.DecimalField(decimal_places=2, default=0, help_text='Loan-linked insurance', max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, help_text='Initial down payment', max_digits=12)),
                ('collateral_value', models.DecimalField(decimal_places=2, default=0, help_text='Vehicle/collateral value at disbursement', max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('defaulted', 'Defaulted'), ('restructured', 'Restructured'), ('pending', 'Pending Disbursement')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(help_text='The vehicle financed under this loan.', on_delete=django.db.models.deletion.PROTECT, related_name='financing_loans', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Financing Loan',
                'verbose_name_plural': 'Financing Loans',
                'ordering': ['-disbursement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalment_no', models.IntegerField(default=1, help_text='Instalment sequence number')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Total instalment amount (principal + interest)', max_digits=12)),
                ('principal_component', models.DecimalField(decimal_places=2, default=0, help_text='Principal portion of this instalment', max_digits=12)),
                ('interest_component', models.DecimalField(decimal_places=2, default=0, help_text='Interest portion of this instalment', max_digits=12)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='upcoming', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount actually paid', max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('auto_debit', 'Auto Debit'), ('other', 'Other')], default='', max_length=20)),
                ('reference_no', models.CharField(blank=True, default='', help_text='Bank reference/transaction ID', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financing.financingloan')),
            ],
            options={
                'verbose_name': 'Financing Payment',
                'verbose_name_plural': 'Financing Payments',
                'ordering': ['due_date', 'instalment_no'],
            },
        ),
        migrations.AddIndex(
            model_name='financingloan',
            index=models.Index(fields=['status'], name='financing_f_status_7338a5_idx'),
        ),
        migrations.AddIndex(
            model_name='financingloan',
            index=models.Index(fields=['bank_name'], name='financing_f_bank_na_d41a88_idx'),
        ),
        migrations.AddIndex(
            model_name='financingloan',
            index=models.Index(fields=['disbursement_date'], name='financing_f_disburs_298f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='financingpayment',
            index=models.Index(fields=['status'], name='financing_f_status_2e92fc_idx'),
        ),
        migrations.AddIndex(
            model_name='financingpayment',
            index=models.Index(fields=['due_date'], name='financing_f_due_dat_800004_idx'),
        ),
        migrations.AddIndex(
            model_name='financingpayment',
            index=models.Index(fields=['loan', 'instalment_no'], name='financing_f_loan_id_743bd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financingpayment',
            unique_together={('loan', 'instalment_no')},
        ),
    ]
