# Generated by Django 6.0.4 on 2026-08-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financingpayment',
            name='evidence_file',
            field=models.FileField(blank=True, help_text='Upload payment evidence (receipt, screenshot, bank confirmation)', null=True, upload_to='financing/'),
        ),
    ]
