# Generated by Django 6.0.4 on 2026-09-05 20:20

import apps.transfers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_license_class_ab_bauto'),
        ('vehicles', '0011_vehicle_type_freeform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.transfers.models._generate_ref, editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('assigned', 'Assigned'), ('en_route', 'En Route'), ('picked_up', 'Picked Up'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='draft', max_length=20)),
                ('trip_type', models.CharField(choices=[('one_way', 'One-Way'), ('round_trip', 'Round Trip'), ('hourly', 'Hourly Hire')], default='one_way', max_length=20)),
                ('service_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('premium', 'Premium'), ('luxury', 'Luxury'), ('van', 'Van / Minibus'), ('executive', 'Executive')], default='business', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_email', models.EmailField(blank=True, max_length=254)),
                ('passenger_phone', models.CharField(blank=True, max_length=40)),
                ('passenger_count', models.PositiveSmallIntegerField(default=1, help_text='Number of passengers incl. children')),
                ('luggage_count', models.PositiveSmallIntegerField(default=0, help_text='Number of luggage pieces')),
                ('has_child_seat', models.BooleanField(default=False)),
                ('has_infant_seat', models.BooleanField(default=False)),
                ('passenger_notes', models.TextField(blank=True, help_text='Special requests, accessibility needs, etc.')),
                ('pickup_name', models.CharField(help_text='Place name e.g. "JFK International Airport Terminal 4"', max_length=300)),
                ('pickup_address', models.TextField()),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pickup_datetime', models.DateTimeField()),
                ('pickup_flight_no', models.CharField(blank=True, help_text='Flight / train number for meet-and-greet tracking', max_length=40)),
                ('dropoff_name', models.CharField(help_text='Place name e.g. "Hilton Garden Inn, Manhattan"', max_length=300)),
                ('dropoff_address', models.TextField()),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('dropoff_datetime', models.DateTimeField(blank=True, null=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, help_text='Estimated route distance', max_digits=10)),
                ('estimated_duration_min', models.PositiveIntegerField(default=0, help_text='Estimated trip duration in minutes')),
                ('tolls_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meet_greet_fee', models.DecimalField(decimal_places=2, default=0, help_text='Meet-and-greet service fee', max_digits=12)),
                ('waiting_fee', models.DecimalField(decimal_places=2, default=0, help_text='Waiting-time charges', max_digits=12)),
                ('child_seat_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('driver_tip', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Sales tax / VAT percentage applied', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('return_datetime', models.DateTimeField(blank=True, help_text='Return pickup time for round-trip bookings', null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, help_text='cash, card, paypal, bank_transfer', max_length=30)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction reference', max_length=120)),
                ('actual_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('actual_dropoff_time', models.DateTimeField(blank=True, null=True)),
                ('driver_current_lat', models.FloatField(blank=True, null=True)),
                ('driver_current_lng', models.FloatField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1–5 passenger rating', null=True)),
                ('feedback', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not shown to passenger)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recurring_id', models.IntegerField(blank=True, db_index=True, help_text='ID of recurring schedule if applicable', null=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'contact_type': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='contacts.contact')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-pickup_datetime'],
            },
        ),
        migrations.CreateModel(
            name='TransferDriverOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quoted_eta_min', models.PositiveIntegerField(default=0, help_text='Minutes driver expects to arrive at pickup')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(limit_choices_to={'contact_type': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_offers', to='contacts.contact')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_offers', to='transfers.transfer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_offers', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['quoted_eta_min', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0, help_text='Order of this stop along the route')),
                ('place_name', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('duration_min', models.PositiveIntegerField(default=0, help_text='Planned stop duration in minutes')),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transfers.transfer')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status'], name='transfers_t_status_91e571_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['pickup_datetime'], name='transfers_t_pickup__8cfb95_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['vehicle'], name='transfers_t_vehicle_211573_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['driver'], name='transfers_t_driver__02d13c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transferdriveroffer',
            unique_together={('transfer', 'driver')},
        ),
    ]
