# Generated by Django 6.0.4 on 2026-07-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('locations', '0001_initial'),
        ('vehicles', '0004_vehicle_lifecycle_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enter', 'Enter'), ('exit', 'Exit')], max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.location')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='TelematicsDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('geotab', 'Geotab'), ('samsara', 'Samsara'), ('keeptruckin', 'KeepTruckin (Motive)'), ('verizon', 'Verizon Connect'), ('generic', 'Generic / Custom')], default='generic', max_length=20)),
                ('imei', models.CharField(blank=True, db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('offline', 'Offline')], default='active', max_length=20)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('last_heading', models.FloatField(blank=True, help_text='Degrees 0-360', null=True)),
                ('last_speed', models.FloatField(blank=True, help_text='Speed in vehicle.mileage_unit per hour', null=True)),
                ('last_ignition_on', models.BooleanField(default=True)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telematics_devices', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_latitude', models.FloatField(blank=True, null=True)),
                ('start_longitude', models.FloatField(blank=True, null=True)),
                ('start_address', models.CharField(blank=True, max_length=300)),
                ('start_odometer', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('end_latitude', models.FloatField(blank=True, null=True)),
                ('end_longitude', models.FloatField(blank=True, null=True)),
                ('end_address', models.CharField(blank=True, max_length=300)),
                ('end_odometer', models.FloatField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('distance', models.FloatField(default=0, help_text='Distance traveled in the vehicle mileage unit')),
                ('duration_minutes', models.FloatField(default=0)),
                ('max_speed', models.FloatField(blank=True, null=True)),
                ('idle_minutes', models.FloatField(default=0)),
                ('harsh_braking_events', models.IntegerField(default=0)),
                ('harsh_acceleration_events', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='telematics.telematicsdevice')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='contacts.contact')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('heading', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('ignition_on', models.BooleanField(default=True)),
                ('odometer', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='telematics.telematicsdevice')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='telematicsdevice',
            index=models.Index(fields=['provider', 'status'], name='telematics__provide_0af2da_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle', 'started_at'], name='telematics__vehicle_38caf4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(fields=['vehicle', 'recorded_at'], name='telematics__vehicle_35331d_idx'),
        ),
    ]
