# Generated by Django 6.0.4 on 2026-07-31 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telematics', '0001_initial'),
        ('vehicles', '0011_vehicle_type_freeform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telematicsdevice',
            name='idle_threshold_minutes',
            field=models.FloatField(default=10, help_text='Minutes of inactivity before idle alert'),
        ),
        migrations.AddField(
            model_name='telematicsdevice',
            name='low_fuel_threshold',
            field=models.FloatField(blank=True, help_text='Fuel % threshold for low-fuel alert', null=True),
        ),
        migrations.AddField(
            model_name='telematicsdevice',
            name='speed_limit',
            field=models.FloatField(blank=True, help_text='Speed limit in vehicle.mileage_unit per hour', null=True),
        ),
        migrations.CreateModel(
            name='TelematicsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('speeding', 'Speeding'), ('idle', 'Excessive Idle'), ('harsh_braking', 'Harsh Braking'), ('harsh_acceleration', 'Harsh Acceleration'), ('geofence_violation', 'Geofence Violation'), ('device_offline', 'Device Offline'), ('low_battery', 'Low Battery'), ('odometer_tamper', 'Odometer Tamper'), ('ignition_off', 'Unexpected Ignition Off'), ('low_fuel', 'Low Fuel')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, help_text='Threshold value that was exceeded', null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='telematics.telematicsdevice')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telematics_alerts', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['alert_type', 'severity'], name='telematics__alert_t_ac0173_idx'), models.Index(fields=['acknowledged', 'triggered_at'], name='telematics__acknowl_b7c946_idx')],
            },
        ),
    ]
